services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports: 
      - 27017:27017
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-alpine
    ports:
      - 5672:5672 
      - 15672:15672  
  handler:
    container_name: handler
    image: handler-console
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Handler/External/Presentation/Dockerfile
  punter:
    container_name: punter
    image: punter-console
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Punter/External/Presentation/Dockerfile